- id: data
  type: DialogDataLayerNode
  conf:
    batch_size: 128
    corpus_name: cornell
    datafile: notebooks/movie_data.txt
    min_count: 3
  inputs: {}
  module: nemo_modules
- id: encoder
  type: EncoderRNNNode
  conf:
    voc_size: 6107
    encoder_n_layers: 2
    hidden_size: 512
    dropout: 0.1
    bidirectional: true
  inputs:
    input_lengths: data.src_lengths
    input_seq: data.src
  module: nemo_modules
- id: greedy_decoder
  type: GreedyLuongAttnDecoderRNNNode
  conf:
    attn_model: dot
    hidden_size: 512
    voc_size: 6107
    decoder_n_layers: 2
    dropout: 0.1
    max_dec_steps: 10
  inputs:
    encoder_outputs: encoder_eval.outputs
    in_nm: decoder.out_nm
  module: nemo_modules
- id: decoder
  type: LuongAttnDecoderRNNNode
  conf:
    attn_model: dot
    hidden_size: 512
    voc_size: 6107
    decoder_n_layers: 2
    dropout: 0.1
  inputs:
    targets: data.tgt
    encoder_outputs: encoder.outputs
    max_target_len: data.max_tgt_lengths
  module: nemo_modules
- id: loss
  type: MaskedXEntropyLossNode
  conf: {}
  inputs:
    predictions: decoder.outputs
    target: data.tgt
    mask: data.mask
  module: nemo_modules
- id: ""
  type: Output_Collector
  conf: {}
  inputs:
    in1: inference.torch_tensor
- id: train
  type: NemoTrainNode
  conf:
    parameters:
      tensors_to_optimize:
        - loss@loss
      batches_per_step: 1
      stop_on_nan_loss: false
      synced_batchnorm: false
      synced_batchnorm_groupsize: 0
      gradient_predivide: false
      amp_max_loss_scale: 16777216
      reset: false
    check_point:
      load_from_folder: null
      checkpoints_to_keep: 4
      force_load: false
      folder: nemo_log
    simple_logger:
      step_freq: 100
      tensors_to_log:
        - loss@loss
    eval_callback:
      eval_step: 100
      eval_tensors:
        - eval_loss@loss
    warmup_policy: {}
    optimizer:
      parameters:
        num_epochs: 3
        lr: 0.001
        betas:
          - 0.9
          - 0.999
        eps: 1e-8
        weight_decay: 0
        amsgrad: false
        momentum: 0.9
      name: adam
  inputs:
    loss@loss: loss.loss
    eval_loss@loss: eval_loss.loss
- id: inference
  type: NemoInferNode
  conf:
    tensors:
      - eval_loss@loss
      - eval_data@src
      - greedy_decoder@outputs
      - eval_data@tgt
    checkpoint_dir: null
    ckpt_pattern: ""
    verbose: true
    cache: false
    use_cache: false
    offload_to_cpu: true
  inputs:
    log_dir: train.checkpoint_dir
    eval_data@tgt: eval_data.tgt
    eval_data@src: eval_data.src
    greedy_decoder@outputs: greedy_decoder.outputs
    eval_loss@loss: eval_loss.loss
- id: eval_data
  type: DialogDataLayerNode
  conf:
    batch_size: 128
    corpus_name: cornell_eval
    datafile: notebooks/movie_data.txt
    min_count: 3
  inputs: {}
  module: nemo_modules
- id: encoder_eval
  type: EncoderRNNNode
  conf:
    voc_size: 6107
    encoder_n_layers: 2
    hidden_size: 512
    dropout: 0.1
    bidirectional: true
    share_weight: Reuse
  inputs:
    input_seq: eval_data.src
    input_lengths: eval_data.src_lengths
    in_nm: encoder.out_nm
  module: nemo_modules
- id: decoder_eval
  type: LuongAttnDecoderRNNNode
  conf:
    attn_model: dot
    hidden_size: 512
    voc_size: 6107
    decoder_n_layers: 2
    dropout: 0.1
    share_weight: Reuse
  inputs:
    targets: eval_data.tgt
    encoder_outputs: encoder_eval.outputs
    max_target_len: eval_data.max_tgt_lengths
    in_nm: decoder.out_nm
  module: nemo_modules
- id: eval_loss
  type: MaskedXEntropyLossNode
  conf: {}
  inputs:
    predictions: decoder_eval.outputs
    target: eval_data.tgt
    mask: eval_data.mask
  module: nemo_modules
